\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{company_analysis}[2021/01/25 Company Analysis class]


\newcommand{\headlinecolor}{\normalcolor}
\LoadClass[11pt]{scrartcl}

\RequirePackage{selinput}
\RequirePackage{layouts}
\RequirePackage{printlen}
\RequirePackage{calculator}
\RequirePackage{geometry}
\RequirePackage{enumitem,varwidth}
\RequirePackage[svgnames]{xcolor}
\RequirePackage{tikz}
\RequirePackage{pgf-pie}
\RequirePackage{lmodern}
\RequirePackage{environ}
\RequirePackage{wrapfig}
\RequirePackage{fdsymbol}
\RequirePackage{fontawesome}
\RequirePackage{graphicx}
\RequirePackage{siunitx}
\RequirePackage{csquotes}
\RequirePackage[gen]{eurosym}
\RequirePackage{caption}

